@startuml
!include ../../../images/common-sequence.iuml

title delete-func-api-ota-get\n(GitHub Action → CloudFormation)

actor "GitHub Actions Runner" as GHA

box "AWS" #ffdbbb
    participant "CloudFormation / SAM" as CF
    participant "API Gateway" as APIGW
end box

GHA -> CF++ : SAM delete\nstack: firefly-func-api-ota-get
CF -> APIGW : Remove route\nGET /ota/{class}/{product_hex}
CF --> GHA-- : DELETE_COMPLETE

@enduml
